<?php

declare(strict_types=1);

/**
 * Collect every translatable string from the PHP sources into
 * lang/songwunsch.pot and report what each lang/*.po is missing.
 *
 *   php tools/extract-strings.php            # write the .pot, print a report
 *   php tools/extract-strings.php --check    # report only, exit 1 if a .po is incomplete
 *
 * Recognised calls (string literals only):
 *   t('message')                    t('message', [...], 'context')
 *   tn('singular', 'plural', $n)    tn('singular', 'plural', $n, [...], 'context')
 *
 * Translators start a new language by copying the .pot to lang/<code>.po,
 * filling in the header (Language, Plural-Forms, X-Native-Name) and the
 * msgstr lines. Nothing else is needed for the language to appear in the app.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root  = dirname(__DIR__);
$check = in_array('--check', $argv, true);

$files = array_merge(
    [$root . '/index.php'],
    glob($root . '/src/*.php') ?: [],
    glob($root . '/templates/*.php') ?: [],
);

/** @var array<string,array{msgid:string,plural:?string,context:?string,refs:array<int,string>}> $entries */
$entries = [];

foreach ($files as $file) {
    $tokens = token_get_all((string) file_get_contents($file));
    $count  = count($tokens);

    for ($i = 0; $i < $count; $i++) {
        $tok = $tokens[$i];
        if (!is_array($tok) || $tok[0] !== T_STRING || !in_array($tok[1], ['t', 'tn'], true)) {
            continue;
        }
        // Skip method calls ($x->t()), static references and the function
        // declarations themselves ("function t(").
        $j = $i - 1;
        while ($j >= 0 && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) {
            $j--;
        }
        $prev = $tokens[$j] ?? null;
        if (is_array($prev) && in_array($prev[0], [T_OBJECT_OPERATOR, T_NULLSAFE_OBJECT_OPERATOR, T_DOUBLE_COLON, T_FUNCTION], true)) {
            continue;
        }
        if (($tokens[$i + 1] ?? null) !== '(') {
            continue;
        }

        $args = extractArgs($tokens, $i + 2);
        $line = $tok[2];
        $name = $tok[1];

        $msgid   = literal($args[0] ?? null);
        $plural  = $name === 'tn' ? literal($args[1] ?? null) : null;
        $context = literal($args[$name === 'tn' ? 4 : 2] ?? null);

        if ($msgid === null || ($name === 'tn' && $plural === null)) {
            // The i18n machinery itself forwards variables -- no warning there.
            if (!in_array(basename($file), ['bootstrap.php', 'Translator.php'], true)) {
                fwrite(STDERR, sprintf("warning: non-literal %s() call in %s:%d\n", $name, relative($file, $root), $line));
            }
            continue;
        }

        $key = ($context !== null ? $context . "\x04" : '') . $msgid;
        $entries[$key] ??= ['msgid' => $msgid, 'plural' => $plural, 'context' => $context, 'refs' => []];
        $entries[$key]['refs'][] = relative($file, $root) . ':' . $line;
        if ($plural !== null) {
            $entries[$key]['plural'] = $plural;
        }
    }
}

ksort($entries, SORT_STRING);

// ---- Write the template ------------------------------------------------------
$pot = "# Songwunsch -- translation template. Generated by tools/extract-strings.php; do not edit by hand.\n"
    . "msgid \"\"\nmsgstr \"\"\n"
    . "\"Project-Id-Version: Songwunsch\\n\"\n"
    . "\"MIME-Version: 1.0\\n\"\n"
    . "\"Content-Type: text/plain; charset=UTF-8\\n\"\n"
    . "\"Content-Transfer-Encoding: 8bit\\n\"\n"
    . "\"Language: \\n\"\n"
    . "\"Plural-Forms: nplurals=2; plural=(n != 1);\\n\"\n"
    . "\"X-Native-Name: \\n\"\n\n";

foreach ($entries as $entry) {
    $pot .= '#: ' . implode(' ', array_unique($entry['refs'])) . "\n";
    if ($entry['context'] !== null) {
        $pot .= 'msgctxt ' . quote($entry['context']) . "\n";
    }
    $pot .= 'msgid ' . quote($entry['msgid']) . "\n";
    if ($entry['plural'] !== null) {
        $pot .= 'msgid_plural ' . quote($entry['plural']) . "\n";
        $pot .= "msgstr[0] \"\"\nmsgstr[1] \"\"\n\n";
    } else {
        $pot .= "msgstr \"\"\n\n";
    }
}

if (!$check) {
    file_put_contents($root . '/lang/songwunsch.pot', $pot);
    printf("lang/songwunsch.pot written: %d messages\n", count($entries));
} else {
    printf("%d messages in the sources\n", count($entries));
}

// ---- Compare with every .po ------------------------------------------------
require $root . '/src/bootstrap.php';

$incomplete = false;

foreach (glob($root . '/lang/*.po') ?: [] as $poFile) {
    $po       = Songwunsch\PoFile::load($poFile);
    $missing  = [];
    $obsolete = [];

    foreach ($entries as $key => $entry) {
        if (!isset($po->messages[$key])) {
            $missing[] = $entry['msgid'];
        }
    }
    foreach (array_keys($po->messages) as $key) {
        if (!isset($entries[$key])) {
            $obsolete[] = str_contains($key, "\x04") ? explode("\x04", $key, 2)[1] : $key;
        }
    }

    printf(
        "%s: %d translated, %d missing, %d obsolete\n",
        relative($poFile, $root),
        count($entries) - count($missing),
        count($missing),
        count($obsolete),
    );
    foreach ($missing as $m) {
        echo "  missing:  " . $m . "\n";
    }
    foreach ($obsolete as $o) {
        echo "  obsolete: " . $o . "\n";
    }
    if ($missing !== []) {
        $incomplete = true;
    }
}

exit($check && $incomplete ? 1 : 0);

// ---- Helpers -----------------------------------------------------------------

/**
 * Split the tokens of a call's argument list (starting after the opening
 * parenthesis) into top-level arguments.
 *
 * @param array<int,mixed> $tokens
 * @return array<int,array<int,mixed>>
 */
function extractArgs(array $tokens, int $start): array
{
    $args  = [[]];
    $depth = 0;
    $n     = count($tokens);

    for ($i = $start; $i < $n; $i++) {
        $tok = $tokens[$i];
        if (is_array($tok) && in_array($tok[0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)) {
            continue;
        }
        if ($tok === '(' || $tok === '[' || (is_array($tok) && $tok[0] === T_CURLY_OPEN)) {
            $depth++;
        } elseif ($tok === ')' || $tok === ']' || $tok === '}') {
            if ($depth === 0) {
                break;
            }
            $depth--;
        } elseif ($tok === ',' && $depth === 0) {
            $args[] = [];
            continue;
        }
        $args[count($args) - 1][] = $tok;
    }

    return $args;
}

/** A single-quoted or double-quoted string literal (possibly concatenated), else null. */
function literal(?array $arg): ?string
{
    if ($arg === null || $arg === []) {
        return null;
    }

    $out = '';
    foreach ($arg as $tok) {
        if ($tok === '.') {
            continue;
        }
        if (!is_array($tok) || $tok[0] !== T_CONSTANT_ENCAPSED_STRING) {
            return null;
        }
        $raw = $tok[1];
        $q   = $raw[0];
        $inner = substr($raw, 1, -1);
        $out .= $q === "'"
            ? strtr($inner, ["\\'" => "'", '\\\\' => '\\'])
            : stripcslashes($inner);
    }

    return $out;
}

function quote(string $value): string
{
    return '"' . strtr($value, ['\\' => '\\\\', '"' => '\\"', "\n" => '\\n', "\t" => '\\t']) . '"';
}

function relative(string $path, string $root): string
{
    return ltrim(str_replace($root, '', $path), '/');
}
